# Site settings
title: 'Утонувшая во Вселенной'
url: 'http://undead.neofusion.ru'
description: 'Блог о программизме, психоанализе и жизни в потенциальном изобилии ресурсов.'

# Build settings
exclude: ['Gemfile']

future: true

gems:
  - jekyll-paginate

markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->

permalink: pretty
timezone: Europe/Moscow

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      disable: true

paginate: 5
